name: Debug Build

on: [push]

jobs:
  debug-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show structure
      run: |
        Get-ChildItem -Recurse | Select-Object FullName
    
    - name: Configure
      run: cmake -B build -A Win32
    
    - name: Build
      run: cmake --build build --config Release --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lg-reminder-${{ github.sha }}
        path: build/Release/lg-reminder.exe
        if-no-files-found: error
